import eslint from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import prettier from 'eslint-config-prettier';
import tseslint from 'typescript-eslint';

export default tseslint.config(
    {
        ignores: ['dist/**', 'node_modules/**', 'coverage/**'],
    },
    eslint.configs.recommended,
    ...tseslint.configs.recommended,
    prettier,
    {
        plugins: {
            '@stylistic': stylistic,
        },
        languageOptions: {
            parserOptions: {
                projectService: true,
                tsconfigRootDir: import.meta.dirname,
            },
        },
        rules: {
            '@stylistic/type-annotation-spacing': [
                'error',
                {
                    before: true,
                    after: true,
                    overrides: {
                        colon: {
                            before: false,
                            after: true,
                        },
                    },
                },
            ],
            '@stylistic/member-delimiter-style': [
                'error',
                {
                    multiline: {
                        delimiter: 'semi',
                        requireLast: true,
                    },
                    singleline: {
                        delimiter: 'comma',
                        requireLast: false,
                    },
                },
            ],
            '@stylistic/indent': ['error', 4],
            '@typescript-eslint/naming-convention': [
                'error',
                {
                    selector: 'interface',
                    format: ['PascalCase'],
                },
            ],
            '@typescript-eslint/no-unused-vars': 'off',
            '@typescript-eslint/no-use-before-define': [
                'error',
                {
                    classes: true,
                    functions: true,
                    variables: true,
                },
            ],
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-require-imports': 'off',
            'accessor-pairs': 'error',
            'array-callback-return': 'off',
            'arrow-body-style': 'error',
            'block-scoped-var': 'error',
            complexity: 'off',
            curly: 'error',
            'default-case': 'error',
            'default-case-last': 'error',
            'default-param-last': 'error',
            'dot-notation': 'off',
            eqeqeq: 'error',
            'grouped-accessor-pairs': 'error',
            'guard-for-in': 'error',
            'id-length': ['error', { max: 50, min: 1 }],
            'lines-between-class-members': 'error',
            'max-nested-callbacks': 'error',
            'max-statements-per-line': 'error',
            'new-cap': 'off',
            'no-alert': 'error',
            'no-array-constructor': 'error',
            'no-async-promise-executor': 'warn',
            'no-caller': 'error',
            'no-case-declarations': 'warn',
            'no-console': ['warn', { allow: ['warn', 'error'] }],
            'no-constructor-return': 'error',
            'no-div-regex': 'error',
            'no-duplicate-imports': 'error',
            'no-else-return': 'error',
            'no-empty-function': 'off',
            'no-eq-null': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-label': 'error',
            'no-implicit-coercion': 'error',
            'no-implicit-globals': 'error',
            'no-implied-eval': 'error',
            'no-inline-comments': 'error',
            'no-invalid-this': 'error',
            'no-iterator': 'error',
            'no-label-var': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-loop-func': 'error',
            'no-multi-assign': 'error',
            'no-multi-str': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-octal-escape': 'error',
            'no-param-reassign': 'off',
            'no-plusplus': 'off',
            'no-proto': 'error',
            'no-restricted-exports': 'error',
            'no-restricted-globals': 'error',
            'no-restricted-imports': 'error',
            'no-return-assign': 'off',
            'no-script-url': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-template-curly-in-string': 'error',
            'no-ternary': 'off',
            'no-throw-literal': 'error',
            'no-undef-init': 'error',
            'no-unmodified-loop-condition': 'error',
            'no-unneeded-ternary': 'error',
            'no-unreachable-loop': 'error',
            'no-unused-expressions': 'warn',
            'no-unused-vars': 'warn',
            'no-useless-call': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-concat': 'error',
            'no-useless-constructor': 'off',
            'no-useless-escape': 'off',
            'no-useless-rename': 'error',
            'no-useless-return': 'error',
            'no-var': 'error',
            'no-void': 'off',
            'no-warning-comments': [1, { terms: ['todo'] }],
            'object-shorthand': 'error',
            'one-var': ['error', 'never'],
            'operator-assignment': 'error',
            'prefer-arrow-callback': 'error',
            'prefer-const': 'error',
            'prefer-exponentiation-operator': 'error',
            'prefer-named-capture-group': 'off',
            'prefer-numeric-literals': 'error',
            'prefer-object-spread': 'error',
            'prefer-promise-reject-errors': 'error',
            'prefer-regex-literals': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            quotes: ['error', 'single'],
            radix: 'error',
            'require-await': 'warn',
            semi: 'error',
            'sort-imports': [
                'error',
                {
                    ignoreDeclarationSort: true,
                    ignoreMemberSort: true,
                },
            ],
            strict: 'error',
            'symbol-description': 'error',
            yoda: 'error',
        },
    },
);
